name: 🐛 Bug Report
description: Report a bug or issue with Spectrum Loot Helper
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Tell us how to reproduce this bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Do '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened instead.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: wow-version
    attributes:
      label: WoW Version
      description: What version of World of Warcraft are you using?
      placeholder: "e.g., 10.2.7, 11.0.2"
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Addon Version
      description: What version of Spectrum Loot Helper are you using?
      placeholder: "e.g., 0.1.0-beta"
    validations:
      required: true

  - type: dropdown
    id: guild-member
    attributes:
      label: Guild Membership
      description: Are you a member of Spectrum Federation?
      options:
        - "Yes - Spectrum Federation member"
        - "No - Testing for the guild"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: 🖼️ Screenshots/Error Messages
      description: If applicable, paste any Lua errors or attach screenshots.
      placeholder: Paste error messages here or describe what screenshots show...
      render: text

  - type: textarea
    id: other-addons
    attributes:
      label: 📦 Other Addons
      description: List other addons you have installed, especially loot-related ones.
      placeholder: "e.g., Details!, WeakAuras, RCLootCouncil, etc."

  - type: dropdown
    id: content-type
    attributes:
      label: 🎮 Content Type
      description: What type of content were you doing when this occurred?
      options:
        - "Guild Raid (Normal)"
        - "Guild Raid (Heroic)"
        - "Guild Raid (Mythic)"
        - "Mythic+ Dungeon"
        - "Normal Dungeon"
        - "PUG Raid"
        - "Other"

  - type: dropdown
    id: loot-mode
    attributes:
      label: Loot Distribution Mode
      description: What loot mode was active?
      options:
        - "Personal Loot"
        - "Group Loot"
        - "Master Loot"
        - "Unknown"

  - type: textarea
    id: additional-context
    attributes:
      label: 🔍 Additional Context
      description: |
        Add any other context about the problem here:
        - When did this first start happening?
        - Does it happen consistently or randomly?
        - Any workarounds you've found?
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have tested with minimal addons to rule out conflicts
          required: true
        - label: I can reproduce this issue consistently
          required: false
        - label: I am running the latest version of the addon
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        **For Guild Members**: Please also mention this in the Discord development channel for faster response during raid times.
